//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddBloodSugar
    {
        public int BloodSugarID { get; set; }
        public int UserId { get; set; }
        public int BloodSugarValue { get; set; }
        public Nullable<System.DateTime> BloodSugarEntranceDate { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
