//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCExample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiabetEntities : DbContext
    {
        public DiabetEntities()
            : base("name=DiabetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<UserDetail> UserDetail { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<RequestContactList> RequestContactList { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagramsSet { get; set; }
        public virtual DbSet<ContactList> ContactList { get; set; }
        public virtual DbSet<AddBloodSugar> AddBloodSugar { get; set; }
        public virtual DbSet<DietList> DietList { get; set; }
        public virtual DbSet<RecoverAccount2> RecoverAccount2 { get; set; }
        public virtual DbSet<Popular> Popular { get; set; }
    }
}
