//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoverAccount2
    {
        public string Email { get; set; }
        public long Key { get; set; }
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual RecoverAccount2 RecoverAccount21 { get; set; }
        public virtual RecoverAccount2 RecoverAccount22 { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
