//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCExample.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.Message = new HashSet<Message>();
            this.Message1 = new HashSet<Message>();
            this.RequestContactList = new HashSet<RequestContactList>();
            this.RequestContactList1 = new HashSet<RequestContactList>();
            this.Login = new HashSet<Login>();
            this.ContactList = new HashSet<ContactList>();
            this.ContactList1 = new HashSet<ContactList>();
            this.AddBloodSugar = new HashSet<AddBloodSugar>();
            this.DietList = new HashSet<DietList>();
            this.DietList1 = new HashSet<DietList>();
            this.RecoverAccount2 = new HashSet<RecoverAccount2>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public string ShortCV { get; set; }

        [Required]
        [EmailAddress]
        public string Mail { get; set; }
        [Required]
        [Phone]
        public string PhoneNumber { get; set; }
        [Required]
       
        public string Username { get; set; }
        public string InsulinUsage { get; set; }
        public string ProfilePictureURL { get; set; }
        public string FileLink { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> BirthDate2 { get; set; }
        public Nullable<int> Type { get; set; }
        public string PreviousDisease { get; set; }
        public Nullable<double> BMI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestContactList> RequestContactList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestContactList> RequestContactList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactList> ContactList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactList> ContactList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddBloodSugar> AddBloodSugar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DietList> DietList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DietList> DietList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoverAccount2> RecoverAccount2 { get; set; }
    }
}
